_entries/2016-05-04-em-dashes.md
_entries/2016-05-04-hyphens-and-dashes.md
_entries/2016-05-04-keywords.md
_entries/2016-05-04-metadata.md
_entries/2016-05-04-seo-and-metadata.md

Making this work is out of scope for this sprint

Remove links from A-Z to Writing for the web section

---

_includes/footer.html
_includes/head.html
_includes/header.html
_includes/homepage-feature-outline.html
_layouts/home.html
index.md
scss/custom.scss

Will link from relevant cards to this PR.

Bugfixes: grid and responsive fixes -- mostly homepage.

---

_ideas-for-the-future/index.md
_sources/index.md

Also adding " " around value in liquid for consistency.

Improve section page titles to remove repetition

---

_includes/collection-sidebar.html
_includes/header.html
_includes/sidebar-nav-az.html
js/accordion.js
scss/custom.scss

Add responsive accordian submenu and associated grid changes

---

_config.yml

Remove second "to" in home page text.

---

_includes/homepage-feature-outline.html

Pull when convenient and please can @maxious rebase content-design branch? Looks out of whack again.

Fixes to home page 4 Things text

---

index.md

Approved by @libbyv please pull when convenient

Fix for platform text + add link to GOV.AU Guides context

---

_includes/homepage-feature-outline.html

Fix add online word to home

---

_entries/2016-05-04-aboriginal-and-torres-strait-islander-peoples.md

@maxious @klepas could this pull request please be merged into master asap. Thank you.

Updated spelling mistake.

---

_entries/2016-05-04-hyphens-and-dashes.md
_entries/2016-05-04-italics.md
_sources/index.md

@maxious or @klepas or @joolswood  I  have updated the Sources page. Thanks. Laura.

Content design post gg

---

_entries/2016-05-04-hyphens-and-dashes.md
_entries/2016-05-04-numbers.md

Remove other spacings

---

_entries/2016-05-04-pdfs.md

Fix typo in pdf entry

---

_entries/2016-05-04-accessibility.md
_entries/2016-05-04-bold.md
_entries/2016-05-04-capitalisation.md
_entries/2016-05-04-captions.md
_entries/2016-05-04-commas.md
_entries/2016-05-04-documents.md
_entries/2016-05-04-fact-sheets.md
_entries/2016-05-04-hyphens-and-dashes.md
_entries/2016-05-04-italics.md
_entries/2016-05-04-photos.md
_entries/2016-05-04-plain-english.md
_entries/2016-05-04-publications
_entries/2016-05-04-spelling.md
_entries/2016-05-04-time.md
_entries/2016-05-04-titles.md
_entries/2016-05-04-units
_entries/2016-05-04-video.md
_entries/2016-05-04-weights-and-measures.md
az-guide.md

May need future work to get new entries to show up, and anchor links.

Edits from Trisha, Jools and Nigel

---

_config.yml
_entries/2016-05-04-capitalisation.md
_includes/footer.html
_includes/homepage-feature-outline.html
_includes/navigation.html
_updates/index.md

Adds recently updated page. Requested by @libbyv

Add recent updates page

---

_entries/2016-05-04-accessibility.md
_entries/2016-05-04-mobiles.md
_entries/2016-05-04-numbered-lists.md
_updates/index.md

Add inline links

---

_entries/2016-05-04-ellipses.md
_updates/index.md

Remove word

---

_entries/2016-05-04-em-dashes.md
_entries/2016-05-04-hyphens-and-dashes.md
_updates/index.md

Add HTML for em-dash

---

bin/cideploy.sh

Hi @maxious I assume we should do this here too?

Turn off circle.ci output

---

.github/PULL_REQUEST_TEMPLATE.md

Sensible order to DOD
Added 2nd pair of eyes as part of process.

Improved DOD

---

_entries/2016-05-04-commas.md
_entries/2016-05-04-numbers.md
_updates/index.md

Change guidance on commas and numbers, to improve readability.
Correct examples.
This will close #147

Commas in numbers

---

_entries/2016-05-04-alt-text.md
_updates/index.md

Suggestion from @andrew.arch - but still need to check the wording.

Improve guidance for complex images

---

_entries/2016-05-04-per-cent.md
_entries/2016-05-04-symbols-and-characters.md
_entries/2016-05-04-weights-and-measures.md
_updates/index.md

Removed guidance around spelling percentage.
- Not ready to merge.
- Will close #169

Clarify guidance on %

---

_entries/2016-05-04-abbreviations-and-acronyms.md
_entries/2016-05-04-contractions.md
_updates/index.md

- Adds more guidance, as requested, around usage of contractions.
- Removed explanation of contractions to get straight to the style guidance.
- Will close #123

Contractions usage

---

.gitignore

Added sublime project files to gitignore :wrench:
* Making sure sublime project files are ignored

Added sublime project files to gitignore :wrench:
